[project]
name = "python-manish"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.12",
    "loguru>=0.7.3",
    "pandas>=2.2.3",
    "ruff>=0.11.11",
    "uvicorn>=0.34.2",
]
